"""
services/tasks_service.py — Cloud Tasks integration for async SMS dispatch.

Enqueues an HTTP task that POSTs the SMS dispatch payload to the notification
service's own ``/tasks/sms`` endpoint.  This decouples the caller (e.g. the
lead-intake service) from the Twilio call: the caller returns quickly and
Cloud Tasks handles delivery + retry on failure.

Task payload schema (JSON body sent to /tasks/sms)
---------------------------------------------------
    to          : str           — E.164 destination phone
    templateId  : str           — Firestore template document ID
    variables   : dict          — template substitution values
    caseId      : str | null    — associated case ID
    requestId   : str           — upstream trace ID

Queue configuration
-------------------
Cloud Tasks queue name  : settings.cloud_tasks_queue  (default: "sms-dispatch")
Queue region            : settings.cloud_tasks_queue_region
Handler URL             : {notification_service_url}/tasks/sms
OIDC service account    : settings.notification_sa_email

The OIDC token generated by Cloud Tasks is verified in app.py before the
task handler executes.

Retry / deduplication
---------------------
Cloud Tasks retries on any non-2xx response from the handler.  The handler
writes a delivery record on every attempt, so duplicate sends are possible
if Twilio succeeds but Firestore write fails (causing a 500 retry).  Callers
that need guaranteed at-most-once delivery should check for an existing
delivery record with the same requestId before dispatching.
"""
from __future__ import annotations

import json
from datetime import timedelta
from typing import Optional

from google.cloud import tasks_v2
from google.protobuf import duration_pb2, timestamp_pb2
from google.protobuf.timestamp_pb2 import Timestamp

from config import get_settings
from logging_config import get_logger

logger = get_logger(__name__)

_tasks_client: Optional[tasks_v2.CloudTasksClient] = None


def _get_tasks_client() -> tasks_v2.CloudTasksClient:
    """Return the process-level Cloud Tasks client (lazy init)."""
    global _tasks_client
    if _tasks_client is None:
        _tasks_client = tasks_v2.CloudTasksClient()
        logger.info("cloud_tasks_client_initialised")
    return _tasks_client


def _queue_path() -> str:
    """Return the fully-qualified Cloud Tasks queue resource name."""
    settings = get_settings()
    client = _get_tasks_client()
    return client.queue_path(
        settings.gcp_project_id,
        settings.cloud_tasks_queue_region,
        settings.cloud_tasks_queue,
    )


def enqueue_sms(
    to: str,
    template_id: str,
    variables: dict,
    *,
    case_id: Optional[str] = None,
    request_id: Optional[str] = None,
    delay_seconds: int = 0,
) -> str:
    """
    Enqueue an SMS dispatch task in Cloud Tasks.

    Parameters
    ----------
    to:
        E.164 destination phone number.
    template_id:
        Firestore SMS template document ID.
    variables:
        Template variable substitution dict.
    case_id:
        Optional case ID — forwarded to sms_service for delivery record.
    request_id:
        Upstream trace ID — forwarded for correlation.
    delay_seconds:
        Schedule the task this many seconds in the future (default: immediate).

    Returns
    -------
    str
        The Cloud Tasks task name (resource path).

    Raises
    ------
    google.api_core.exceptions.GoogleAPICallError
        On Cloud Tasks API failure.  Caller should treat this as non-fatal and
        log; the SMS can be retried manually or via a monitoring alert.
    """
    settings = get_settings()

    payload = {
        "to": to,
        "templateId": template_id,
        "variables": variables,
        "caseId": case_id,
        "requestId": request_id,
    }

    task: dict = {
        "http_request": {
            "http_method": tasks_v2.HttpMethod.POST,
            "url": f"{settings.notification_service_url}/tasks/sms",
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps(payload).encode("utf-8"),
            "oidc_token": {
                "service_account_email": settings.notification_sa_email,
                "audience": settings.notification_service_url,
            },
        }
    }

    if delay_seconds > 0:
        from google.protobuf import timestamp_pb2 as ts_pb2
        import time

        schedule_time = ts_pb2.Timestamp()
        schedule_time.FromSeconds(int(time.time()) + delay_seconds)
        task["schedule_time"] = schedule_time

    client = _get_tasks_client()
    response = client.create_task(
        request={"parent": _queue_path(), "task": task}
    )

    logger.info(
        "sms_task_enqueued",
        task_name=response.name,
        template_id=template_id,
        case_id=case_id,
        request_id=request_id,
        delay_seconds=delay_seconds,
        to_masked="[REDACTED]",
    )

    return response.name
